"""Ui / wizard custom filters for NN Training Studio."""

from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.backends.backend_tkagg import NavigationToolbar2Tk
from tkinter.scrolledtext import ScrolledText
import json
from tkinter import messagebox
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tkinter as tk
from tkinter import ttk
from nn_training_studio.ai_validation import (
    validate_ai_generation,
)
from nn_training_studio.constants import (
    CUSTOM_FILTER_MODE_EXPERT,
    CUSTOM_FILTER_MODE_SAFE_AI,
    DATA_MODE_IMAGE,
    DEFAULT_CUSTOM_FILTER_CODE,
    OFFICIAL_PROVIDER_SETTINGS,
    TASK_AUTOENCODER,
)
from nn_training_studio.filters import (
    apply_safe_filter_spec,
    compare_filter_result,
    execute_custom_filter_code,
)
from nn_training_studio.templates import (
    make_safe_filter_template,
    make_safe_model_template,
)


class CustomFiltersMixin:
    """CustomFilters behavior for the main application."""

    def build_step_3_custom_filter(self):
        if self.filtered_df is None:
            ttk.Label(
                self.content_frame,
                text="Please complete the built-in filter step first."
            ).pack()
            return

        if self.data_mode_var.get() == DATA_MODE_IMAGE:
            frame = ttk.LabelFrame(
                self.content_frame,
                text="Image Transformation",
            )
            frame.pack(fill=tk.BOTH, expand=True, padx=20, pady=20)
            ttk.Label(
                frame,
                text=(
                    "Custom pandas/Python signal filters are not applied to "
                    "photos. This prevents accidental changes to image paths "
                    "or class labels.\n\n"
                    "Use the next preprocessing page for image resizing, "
                    "colour mode, and safe built-in augmentation."
                ),
                justify=tk.LEFT,
                wraplength=900,
                font=("Arial", 12),
            ).pack(anchor="w", padx=20, pady=20)
            return

        outer = ttk.PanedWindow(self.content_frame, orient=tk.HORIZONTAL)
        outer.pack(fill=tk.BOTH, expand=True, padx=5, pady=5)

        settings_frame = ttk.LabelFrame(
            outer,
            text="Custom Filter Settings"
        )
        preview_frame = ttk.LabelFrame(
            outer,
            text="Custom Filter Preview"
        )
        outer.add(settings_frame, weight=3)
        outer.add(preview_frame, weight=2)

        ttk.Checkbutton(
            settings_frame,
            text="Enable an additional filter after the built-in filter",
            variable=self.custom_filter_enabled_var
        ).pack(anchor="w", padx=8, pady=(8, 4))

        mode_row = ttk.Frame(settings_frame)
        mode_row.pack(fill=tk.X, padx=8, pady=4)
        ttk.Label(
            mode_row,
            text="Execution mode:",
            font=("Arial", 10, "bold"),
        ).pack(side=tk.LEFT, padx=(0, 6))
        mode_combo = ttk.Combobox(
            mode_row,
            textvariable=self.custom_filter_mode_var,
            state="readonly",
            values=[
                CUSTOM_FILTER_MODE_SAFE_AI,
                CUSTOM_FILTER_MODE_EXPERT,
            ],
            width=26,
        )
        mode_combo.pack(side=tk.LEFT)
        mode_combo.bind(
            "<<ComboboxSelected>>",
            self.on_custom_filter_mode_changed,
        )

        warning = ttk.Label(
            settings_frame,
            text=(
                "Safe custom JSON uses only validated allowlisted operations "
                "and can be written manually or generated by AI. "
                "Expert Python mode runs code locally with your Python "
                "permissions; only use code that you trust."
            ),
            foreground="dark red",
            wraplength=650
        )
        warning.pack(anchor="w", padx=8, pady=(0, 8))

        ttk.Label(
            settings_frame,
            text="Select columns supplied to custom_filter():",
            font=("Arial", 10, "bold")
        ).pack(anchor="w", padx=8)

        list_frame = ttk.Frame(settings_frame)
        list_frame.pack(fill=tk.X, padx=8, pady=5)

        self.custom_filter_listbox = tk.Listbox(
            list_frame,
            selectmode=tk.MULTIPLE,
            exportselection=False,
            height=7
        )
        self.custom_filter_listbox.pack(
            side=tk.LEFT,
            fill=tk.BOTH,
            expand=True
        )

        list_scroll = ttk.Scrollbar(
            list_frame,
            orient=tk.VERTICAL,
            command=self.custom_filter_listbox.yview
        )
        list_scroll.pack(side=tk.RIGHT, fill=tk.Y)
        self.custom_filter_listbox.config(yscrollcommand=list_scroll.set)

        current_label = self.label_var.get()
        self.custom_filter_available_cols = [
            col for col in self.filtered_df.columns
            if pd.api.types.is_numeric_dtype(self.filtered_df[col])
            and col != current_label
            and "label" not in col.lower()
            and "target" not in col.lower()
            and "class" not in col.lower()
            and "id" not in col.lower()
        ]

        for col in self.custom_filter_available_cols:
            self.custom_filter_listbox.insert(tk.END, col)

        for i, col in enumerate(self.custom_filter_available_cols):
            if col in self.selected_custom_filter_cols:
                self.custom_filter_listbox.selection_set(i)

        quick_row = ttk.Frame(settings_frame)
        quick_row.pack(fill=tk.X, padx=8, pady=3)

        ttk.Button(
            quick_row,
            text="Select All Signals",
            command=self.select_all_custom_filter_columns
        ).pack(side=tk.LEFT, padx=2)
        ttk.Button(
            quick_row,
            text="Clear Columns",
            command=self.clear_custom_filter_columns
        ).pack(side=tk.LEFT, padx=2)

        ai_designer = ttk.LabelFrame(
            settings_frame,
            text="AI Filter Designer",
        )
        ai_designer.pack(fill=tk.X, padx=8, pady=(7, 4))
        ttk.Label(
            ai_designer,
            text=(
                "Describe the noise, response speed, frequency components, "
                "or signal features that must be preserved:"
            ),
            wraplength=650,
        ).pack(anchor="w", padx=7, pady=(6, 2))
        ttk.Entry(
            ai_designer,
            textvariable=self.custom_filter_ai_prompt_var,
        ).pack(fill=tk.X, padx=7, pady=3)
        ai_filter_action_row = ttk.Frame(ai_designer)
        ai_filter_action_row.pack(fill=tk.X, padx=5, pady=(2, 6))
        ai_filter_action_row.columnconfigure(0, weight=1)
        self.custom_filter_ai_button = ttk.Button(
            ai_filter_action_row,
            text="Generate Customized Filter with AI",
            command=self.start_custom_filter_ai_generation,
            state=(
                tk.NORMAL
                if self.ai_provider_var.get() in OFFICIAL_PROVIDER_SETTINGS
                else tk.DISABLED
            ),
        )
        self.custom_filter_ai_button.grid(
            row=0,
            column=0,
            sticky="w",
            padx=2,
            pady=2,
        )
        ttk.Label(
            ai_filter_action_row,
            text=(
                f"Provider: {self.ai_provider_var.get()} "
                f"| Model: {self.ai_model_var.get() or 'not configured'}"
            ),
            foreground="#245a85",
            wraplength=570,
        ).grid(
            row=1,
            column=0,
            sticky="w",
            padx=4,
            pady=(2, 0),
        )
        self.custom_filter_ai_status_label = ttk.Label(
            ai_filter_action_row,
            text=(
                "Select columns and describe the filter. An analysis "
                "recommendation is not required."
            ),
            foreground="#7a4b00",
            wraplength=570,
        )
        self.custom_filter_ai_status_label.grid(
            row=2,
            column=0,
            sticky="w",
            padx=4,
            pady=(1, 2),
        )

        ttk.Label(
            settings_frame,
            text=(
                "Safe custom JSON or Expert Python function: "
                "custom_filter(df, selected_columns). Both manual and "
                "AI-generated safe JSON are editable and revalidated."
            ),
            font=("Arial", 10, "bold")
        ).pack(anchor="w", padx=8, pady=(8, 2))

        button_row = ttk.Frame(settings_frame)
        button_row.pack(fill=tk.X, padx=8, pady=(3, 5))
        for column_index in range(2):
            button_row.columnconfigure(column_index, weight=1)

        ttk.Button(
            button_row,
            text="Create Safe JSON from Selected Columns",
            command=self.load_safe_filter_template
        ).grid(
            row=0,
            column=0,
            sticky="ew",
            padx=3,
            pady=2,
        )
        ttk.Button(
            button_row,
            text="Load Expert Python Template",
            command=self.load_custom_filter_template
        ).grid(
            row=0,
            column=1,
            sticky="ew",
            padx=3,
            pady=2,
        )
        ttk.Button(
            button_row,
            text="Validate / Apply Edits and Preview",
            command=self.preview_custom_filter_result
        ).grid(
            row=1,
            column=0,
            sticky="ew",
            padx=3,
            pady=2,
        )
        ttk.Button(
            button_row,
            text="Plot Before / After",
            command=self.plot_custom_filter_result,
        ).grid(
            row=1,
            column=1,
            sticky="ew",
            padx=3,
            pady=2,
        )
        ttk.Button(
            button_row,
            text="Skip Custom Filter",
            command=self.skip_custom_filter
        ).grid(
            row=2,
            column=0,
            columnspan=2,
            sticky="ew",
            padx=3,
            pady=2,
        )

        self.custom_filter_code_text = ScrolledText(
            settings_frame,
            wrap=tk.NONE,
            height=10,
            font=("Consolas", 10)
        )
        self.custom_filter_code_text.pack(
            fill=tk.BOTH,
            expand=True,
            padx=8,
            pady=(2, 6)
        )
        self.custom_filter_code_text.insert(tk.END, self.custom_filter_code)

        if self.custom_filter_mode_var.get() == CUSTOM_FILTER_MODE_SAFE_AI:
            self.custom_filter_code_text.delete("1.0", tk.END)
            self.custom_filter_code_text.insert(
                tk.END,
                json.dumps(
                    self.safe_filter_spec or {
                        "status": "No generated safe filter has been approved."
                    },
                    indent=2,
                ),
            )

        custom_preview_notebook = ttk.Notebook(preview_frame)
        custom_preview_notebook.pack(
            fill=tk.BOTH,
            expand=True,
            padx=5,
            pady=5,
        )
        custom_metrics_tab = ttk.Frame(custom_preview_notebook)
        custom_plot_tab = ttk.Frame(custom_preview_notebook)
        custom_preview_notebook.add(
            custom_metrics_tab,
            text="Metrics & Values",
        )
        custom_preview_notebook.add(
            custom_plot_tab,
            text="Signal Plot",
        )
        self.custom_filter_preview_notebook = custom_preview_notebook
        self.custom_filter_preview_text = ScrolledText(
            custom_metrics_tab,
            wrap=tk.WORD
        )
        self.custom_filter_preview_text.pack(
            fill=tk.BOTH,
            expand=True,
            padx=3,
            pady=3
        )
        self.custom_filter_plot_host = ttk.Frame(custom_plot_tab)
        self.custom_filter_plot_host.pack(
            fill=tk.BOTH,
            expand=True,
            padx=3,
            pady=3,
        )
        self.custom_filter_plot_placeholder = ttk.Label(
            self.custom_filter_plot_host,
            text=(
                "Enable a custom filter, select signal columns, and choose\n"
                "Validate / Apply Edits and Preview. The plot updates automatically."
            ),
            foreground="#666666",
            justify=tk.CENTER,
        )
        self.custom_filter_plot_placeholder.pack(
            expand=True, padx=20, pady=20
        )

        if self.custom_filter_enabled_var.get():
            self.preview_custom_filter_result(show_message=False)
        else:
            self.custom_filter_preview_text.insert(
                tk.END,
                "Additional custom filtering is disabled.\n\n"
                "The dataset from the built-in filter step will pass directly "
                "to column selection. You can select columns and ask the AI "
                "Filter Designer to create a safe custom filter."
            )

    def get_custom_filter_code(self):
        if hasattr(self, "custom_filter_code_text"):
            return self.custom_filter_code_text.get("1.0", tk.END).strip()
        return self.custom_filter_code.strip()

    def on_custom_filter_mode_changed(self, event=None):
        if not hasattr(self, "custom_filter_code_text"):
            return
        self.custom_filter_code_text.config(state=tk.NORMAL)
        self.custom_filter_code_text.delete("1.0", tk.END)
        if self.custom_filter_mode_var.get() == CUSTOM_FILTER_MODE_SAFE_AI:
            self.custom_filter_code_text.insert(
                tk.END,
                json.dumps(
                    self.safe_filter_spec or {
                        "status": "No generated safe filter has been approved."
                    },
                    indent=2,
                ),
            )
        else:
            self.custom_filter_code_text.insert(
                tk.END,
                self.custom_filter_code,
            )

    def get_selected_custom_filter_columns(self):
        if (
            self.custom_filter_mode_var.get() == CUSTOM_FILTER_MODE_SAFE_AI
            and self.safe_filter_spec is not None
        ):
            return [
                pipeline["column"]
                for pipeline in self.safe_filter_spec.get("pipelines", [])
            ]
        if not hasattr(self, "custom_filter_listbox"):
            return list(self.selected_custom_filter_cols)

        return [
            self.custom_filter_available_cols[i]
            for i in self.custom_filter_listbox.curselection()
        ]

    def get_safe_filter_spec_from_editor(self):
        if (
            hasattr(self, "custom_filter_code_text")
            and self.custom_filter_mode_var.get()
            == CUSTOM_FILTER_MODE_SAFE_AI
        ):
            text_value = self.custom_filter_code_text.get(
                "1.0", tk.END
            ).strip()
            if not text_value:
                raise ValueError("The safe filter specification is empty.")
            try:
                parsed = json.loads(text_value)
            except json.JSONDecodeError as exc:
                raise ValueError(
                    f"The edited safe filter is not valid JSON: {exc}"
                ) from exc
            if not isinstance(parsed, dict):
                raise ValueError(
                    "The edited safe filter specification must be a JSON object."
                )
            return parsed
        return self.safe_filter_spec

    def validate_safe_filter_for_current_selection(self, filter_spec):
        """Validate safe filter JSON against current columns, independent of AI."""
        selected_columns = []
        if hasattr(self, "custom_filter_listbox"):
            selected_columns = [
                self.custom_filter_available_cols[index]
                for index in self.custom_filter_listbox.curselection()
            ]
        if not selected_columns:
            selected_columns = [
                pipeline.get("column")
                for pipeline in filter_spec.get("pipelines", [])
                if isinstance(pipeline, dict) and pipeline.get("column")
            ]
        if not selected_columns:
            raise ValueError(
                "Select the columns that this safe filter is allowed to modify."
            )

        recommendation = self.build_current_generation_recommendation(
            input_columns=selected_columns,
            component="filter",
        )
        generation = {
            "summary": (
                "Safe filter validated from the user's current selections."
            ),
            "filter_spec": filter_spec,
            # This companion is required only by the shared schema. Filter
            # validation and model customization remain independent.
            "model_spec": make_safe_model_template(
                "Window-based (3D)",
                TASK_AUTOENCODER,
            ),
        }
        generation = validate_ai_generation(
            generation,
            self.dataset_profile,
            recommendation,
        )
        self.safe_filter_generation = generation
        self.safe_filter_recommendation = recommendation
        self.safe_filter_spec = generation["filter_spec"]
        return self.safe_filter_spec, selected_columns

    def select_all_custom_filter_columns(self):
        if hasattr(self, "custom_filter_listbox"):
            self.custom_filter_listbox.selection_set(0, tk.END)

    def clear_custom_filter_columns(self):
        if hasattr(self, "custom_filter_listbox"):
            self.custom_filter_listbox.selection_clear(0, tk.END)

    def start_custom_filter_ai_generation(self):
        if not hasattr(self, "custom_filter_listbox"):
            messagebox.showerror(
                "AI Filter Designer",
                "Open the custom-filter page before generating a filter.",
            )
            return
        selected_columns = [
            self.custom_filter_available_cols[index]
            for index in self.custom_filter_listbox.curselection()
        ]
        if not selected_columns:
            messagebox.showwarning(
                "AI Filter Designer",
                "Select the signal columns that the AI is allowed to filter.",
            )
            return
        self.start_component_ai_generation(
            component="filter",
            customization_prompt=self.custom_filter_ai_prompt_var.get(),
            input_columns=selected_columns,
        )

    def load_safe_filter_template(self):
        """Start a safe editable filter directly from the user's columns."""
        try:
            if not hasattr(self, "custom_filter_listbox"):
                raise ValueError("Open the custom-filter page first.")
            selected_columns = [
                self.custom_filter_available_cols[index]
                for index in self.custom_filter_listbox.curselection()
            ]
            if not selected_columns:
                raise ValueError(
                    "Select at least one signal column before creating the "
                    "safe filter template."
                )
            recommendation = self.build_current_generation_recommendation(
                input_columns=selected_columns,
                component="filter",
            )
            generation = {
                "summary": (
                    "User-created safe filter template. No AI recommendation "
                    "or API request was used."
                ),
                "filter_spec": make_safe_filter_template(selected_columns),
                "model_spec": make_safe_model_template(
                    "Window-based (3D)",
                    TASK_AUTOENCODER,
                ),
            }
            generation = validate_ai_generation(
                generation,
                self.dataset_profile,
                recommendation,
            )
            self.safe_filter_generation = generation
            self.safe_filter_recommendation = recommendation
            self.safe_filter_spec = generation["filter_spec"]
            self.selected_custom_filter_cols = list(selected_columns)
            self.custom_filter_mode_var.set(CUSTOM_FILTER_MODE_SAFE_AI)
            self.custom_filter_enabled_var.set(True)
            self.on_custom_filter_mode_changed()
            if hasattr(self, "custom_filter_ai_status_label"):
                self.custom_filter_ai_status_label.config(
                    text=(
                        "Manual safe template created. Edit its operations and "
                        "parameters, then validate and preview."
                    )
                )
            self.preview_custom_filter_result(show_message=False)
        except Exception as exc:
            messagebox.showerror("Safe Filter Template Error", str(exc))

    def load_custom_filter_template(self):
        self.custom_filter_mode_var.set(CUSTOM_FILTER_MODE_EXPERT)
        self.custom_filter_code = DEFAULT_CUSTOM_FILTER_CODE
        if hasattr(self, "custom_filter_code_text"):
            self.custom_filter_code_text.delete("1.0", tk.END)
            self.custom_filter_code_text.insert(tk.END, self.custom_filter_code)

    def skip_custom_filter(self):
        self.custom_filter_enabled_var.set(False)
        self.selected_custom_filter_cols = []
        self.custom_filtered_df = self.filtered_df.copy()
        self.custom_filter_preview_df = self.filtered_df.copy()
        self.df = self.custom_filtered_df.copy()

        if hasattr(self, "custom_filter_listbox"):
            self.custom_filter_listbox.selection_clear(0, tk.END)

        if hasattr(self, "custom_filter_preview_text"):
            self.custom_filter_preview_text.delete("1.0", tk.END)
            self.custom_filter_preview_text.insert(
                tk.END,
                "Custom filter skipped. Built-in filtered data will be used."
            )
        if hasattr(self, "custom_filter_plot_host"):
            for child in self.custom_filter_plot_host.winfo_children():
                child.destroy()
            self.custom_filter_plot_placeholder = ttk.Label(
                self.custom_filter_plot_host,
                text="Custom filtering is disabled; no comparison plot is active.",
                foreground="#666666",
            )
            self.custom_filter_plot_placeholder.pack(
                expand=True, padx=20, pady=20
            )

    def preview_custom_filter_result(
        self,
        show_message=True,
        refresh_plot=True,
    ):
        try:
            if not self.custom_filter_enabled_var.get():
                self.skip_custom_filter()
                return False

            if (
                self.custom_filter_mode_var.get()
                == CUSTOM_FILTER_MODE_SAFE_AI
            ):
                edited_filter_spec = self.get_safe_filter_spec_from_editor()
                if edited_filter_spec is None:
                    raise ValueError(
                        "Create a safe filter template or generate one with AI."
                    )
                self.safe_filter_spec, allowed_columns = (
                    self.validate_safe_filter_for_current_selection(
                        edited_filter_spec
                    )
                )
                selected_cols = [
                    pipeline["column"]
                    for pipeline in self.safe_filter_spec["pipelines"]
                ]
                if not selected_cols:
                    raise ValueError(
                        "The safe filter has no pipelines. Disable the custom "
                        "filter or add at least one validated pipeline."
                    )
                result = apply_safe_filter_spec(
                    df=self.filtered_df,
                    filter_spec=self.safe_filter_spec,
                    sampling_frequency=self.dataset_profile.get(
                        "sampling_frequency_hz"
                    ),
                    allowed_columns=allowed_columns,
                )
            else:
                selected_cols = self.get_selected_custom_filter_columns()
                if not selected_cols:
                    raise ValueError(
                        "Select at least one column for the custom filter."
                    )
                custom_code = self.get_custom_filter_code()
                result = execute_custom_filter_code(
                    df=self.filtered_df,
                    selected_columns=selected_cols,
                    custom_code=custom_code
                )
                self.custom_filter_code = custom_code
            self.selected_custom_filter_cols = selected_cols
            self.custom_filter_preview_df = result.copy()

            self.custom_filter_preview_text.delete("1.0", tk.END)
            self.custom_filter_preview_text.insert(
                tk.END,
                "Custom filter validated successfully.\n\n"
            )
            self.custom_filter_preview_text.insert(
                tk.END,
                f"Selected columns: {selected_cols}\n"
            )
            self.custom_filter_preview_text.insert(
                tk.END,
                f"Input shape: {self.filtered_df.shape}\n"
                f"Output shape: {result.shape}\n\n"
            )

            if (
                self.custom_filter_mode_var.get()
                == CUSTOM_FILTER_MODE_SAFE_AI
            ):
                metrics = compare_filter_result(
                    self.filtered_df,
                    result,
                    selected_cols,
                )
                self.custom_filter_preview_text.insert(
                    tk.END,
                    "Preservation metrics:\n"
                )
                for metric in metrics:
                    self.custom_filter_preview_text.insert(
                        tk.END,
                        (
                            f"- {metric['column']}: correlation="
                            f"{metric['correlation']:.6f}, RMSE="
                            f"{metric['rmse']:.6g}, std ratio="
                            f"{metric['std_ratio']:.6f}, mean absolute "
                            f"change={metric['mean_absolute_change']:.6g}\n"
                        ),
                    )
                self.custom_filter_preview_text.insert(tk.END, "\n")

            compare_cols = selected_cols[:4]
            for col in compare_cols:
                before = pd.to_numeric(
                    self.filtered_df[col], errors="coerce"
                ).head(10).values
                after = pd.to_numeric(
                    result[col], errors="coerce"
                ).head(10).values
                self.custom_filter_preview_text.insert(
                    tk.END,
                    f"Column: {col}\n"
                    f"Before: {np.round(before, 6)}\n"
                    f"After:  {np.round(after, 6)}\n\n"
                )

            if hasattr(self, "custom_filter_ai_status_label"):
                self.custom_filter_ai_status_label.config(
                    text=(
                        "Custom filter validated. The Signal Plot tab has been "
                        "refreshed and this result will be applied when you "
                        "continue."
                    )
                )

            if show_message:
                messagebox.showinfo(
                    "Custom Filter Valid",
                    "The selected filter was validated successfully."
                )

            if refresh_plot:
                self.after_idle(
                    lambda: self.plot_custom_filter_result(
                        validate_first=False
                    )
                )
            return True

        except Exception as exc:
            if hasattr(self, "custom_filter_preview_text"):
                self.custom_filter_preview_text.delete("1.0", tk.END)
                self.custom_filter_preview_text.insert(
                    tk.END,
                    "Custom filter validation failed.\n\n" + str(exc),
                )
            if hasattr(self, "custom_filter_ai_status_label"):
                self.custom_filter_ai_status_label.config(
                    text="Custom filter validation failed: " + str(exc)
                )
            messagebox.showerror("Custom Filter Error", str(exc))
            return False

    def plot_custom_filter_result(self, validate_first=True):
        """Plot an AI-safe or expert custom filter after local validation."""
        try:
            if validate_first and not self.preview_custom_filter_result(
                show_message=False,
                refresh_plot=False,
            ):
                return
            result = getattr(self, "custom_filter_preview_df", None)
            selected_columns = list(self.selected_custom_filter_cols)
            if result is None or not selected_columns:
                raise ValueError(
                    "Enable and validate a custom filter before plotting."
                )
            if not hasattr(self, "custom_filter_plot_host"):
                raise ValueError("Reopen the custom-filter page and try again.")
            if vars(self).get("custom_filter_plot_figure") is not None:
                plt.close(self.custom_filter_plot_figure)
            for child in self.custom_filter_plot_host.winfo_children():
                child.destroy()

            row_count = len(result)
            step = max(1, int(np.ceil(row_count / 5000)))
            positions = np.arange(0, row_count, step)
            columns_to_plot = selected_columns[:4]
            figure, axes = plt.subplots(
                len(columns_to_plot),
                1,
                figsize=(7.3, max(3.4, 2.45 * len(columns_to_plot))),
                squeeze=False,
                sharex=True,
            )
            for row_index, column in enumerate(columns_to_plot):
                axis = axes[row_index][0]
                before = pd.to_numeric(
                    self.filtered_df.iloc[positions][column],
                    errors="coerce",
                ).to_numpy(dtype=float)
                after = pd.to_numeric(
                    result.iloc[positions][column],
                    errors="coerce",
                ).to_numpy(dtype=float)
                axis.plot(
                    positions,
                    before,
                    label="Before custom filter",
                    color="#777777",
                    alpha=0.72,
                    linewidth=0.9,
                )
                axis.plot(
                    positions,
                    after,
                    label="After custom filter",
                    color="#1769aa",
                    linewidth=1.15,
                )
                axis.set_title(str(column), loc="left", fontsize=10)
                axis.set_ylabel("Amplitude")
                axis.legend(loc="upper right")
                axis.grid(alpha=0.25)
            axes[-1][0].set_xlabel("Sample index")
            figure.suptitle(
                (
                    "Custom filter comparison"
                    + (
                        f" (displaying every {step}th point)"
                        if step > 1
                        else ""
                    )
                ),
                fontsize=11,
            )
            figure.tight_layout()
            canvas = FigureCanvasTkAgg(
                figure,
                master=self.custom_filter_plot_host,
            )
            canvas.draw()
            toolbar = NavigationToolbar2Tk(
                canvas,
                self.custom_filter_plot_host,
                pack_toolbar=False,
            )
            toolbar.update()
            toolbar.pack(side=tk.TOP, fill=tk.X)
            canvas.get_tk_widget().pack(
                side=tk.TOP,
                fill=tk.BOTH,
                expand=True,
            )
            self.custom_filter_plot_canvas = canvas
            self.custom_filter_plot_figure = figure
            self.custom_filter_plot_toolbar = toolbar
            self.custom_filter_preview_notebook.select(1)
            self.custom_filter_plot_host.update_idletasks()
            canvas.draw_idle()
            self.after_idle(
                lambda current_canvas=canvas: self.redraw_embedded_canvas(
                    current_canvas
                )
            )
        except Exception as exc:
            self.show_embedded_plot_message(
                "custom_filter_plot_host",
                "Custom-filter plot could not be rendered:\n" + str(exc),
            )
            messagebox.showerror("Custom Filter Plot Error", str(exc))

    def validate_step_3_custom_filter(self):
        if self.filtered_df is None:
            raise ValueError("Please complete the built-in filter step first.")
        if self.data_mode_var.get() == DATA_MODE_IMAGE:
            self.custom_filter_enabled_var.set(False)
            self.selected_custom_filter_cols = []
            self.custom_filtered_df = self.filtered_df.copy()
            self.df = self.custom_filtered_df.copy()
            self._pending_preparation_steps.discard(3)
            return

        if not self.custom_filter_enabled_var.get():
            self.selected_custom_filter_cols = []
            self.custom_filtered_df = self.filtered_df.copy()
            self.df = self.custom_filtered_df.copy()
            self._pending_preparation_steps.discard(3)
            return

        if self.custom_filter_mode_var.get() == CUSTOM_FILTER_MODE_SAFE_AI:
            edited_filter_spec = self.get_safe_filter_spec_from_editor()
            if edited_filter_spec is None:
                raise ValueError(
                    "Create a safe filter template or generate one with AI."
                )
            self.safe_filter_spec, allowed_columns = (
                self.validate_safe_filter_for_current_selection(
                    edited_filter_spec
                )
            )
            selected_cols = [
                pipeline["column"]
                for pipeline in self.safe_filter_spec["pipelines"]
            ]
            if not selected_cols:
                raise ValueError(
                    "The safe filter has no pipelines. Disable the custom "
                    "filter or add at least one validated pipeline."
                )
            result = apply_safe_filter_spec(
                df=self.filtered_df,
                filter_spec=self.safe_filter_spec,
                sampling_frequency=self.dataset_profile.get(
                    "sampling_frequency_hz"
                ),
                allowed_columns=allowed_columns,
            )
        else:
            selected_cols = self.get_selected_custom_filter_columns()
            if not selected_cols:
                raise ValueError(
                    "Select at least one column for the custom Python filter."
                )
            custom_code = self.get_custom_filter_code()
            result = execute_custom_filter_code(
                df=self.filtered_df,
                selected_columns=selected_cols,
                custom_code=custom_code
            )
            self.custom_filter_code = custom_code
        self.selected_custom_filter_cols = selected_cols
        self.custom_filtered_df = result
        self.df = result.copy()
        self.refresh_recommended_columns_after_data_change()

        messagebox.showinfo(
            "Custom Filter Applied",
            f"{self.custom_filter_mode_var.get()} filter applied successfully."
            "\n\n"
            f"Filtered columns: {selected_cols}"
        )

        self._pending_preparation_steps.discard(3)
